version: "2"

run:
  timeout: 5m
  go: "1.23"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign

    - misspell
    - unconvert
    - unparam
    - revive

  settings:
    revive:
      rules:
        - name: exported
          severity: warning
    govet:
      enable-all: true

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
